"""Adding creation_date and last_update timestamps to game model.

Revision ID: 14f637df1007
Revises: 8c587092fed4
Create Date: 2021-03-12 19:44:42.358695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f637df1007'
down_revision = '8c587092fed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('game', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'last_updated')
    op.drop_column('game', 'created_on')
    # ### end Alembic commands ###
