"""Added field for saving game instructions.

Revision ID: d04a716a324d
Revises: 14f637df1007
Create Date: 2021-03-13 23:07:15.090366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04a716a324d'
down_revision = '14f637df1007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'instructions')
    # ### end Alembic commands ###
